# VIM
alias vi="vim"

# GIT

alias g-s="git status"
alias g-a="git add"
alias g-c="git commit"
alias gw-a="git worktree add"
alias gw-s="git worktree status"
alias gw-r="git worktree remove"
# create an alias that stes the origin to the current worktree

# CONDA
alias ca='conda activate'
alias cda='conda deactivate'
alias cie='conda info --envs'

# PYTHON
alias p='python'
alias install-pytorch="conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia"

# JUPYTER
alias jupyter-remote="jupyter notebook --no-browser --port=8888 --NotebookApp.iopub_data_rate_limit=1.0e10"
alias create-ja-pair="python -m jupyter_ascending.scripts.make_pair --base"
alias install-ja-in-this-venv="pip install jupyter_ascending;jupyter nbextension install --py --sys-prefix jupyter_ascending;jupyter nbextension     enable jupyter_ascending --sys-prefix --py;jupyter serverextension enable jupyter_ascending --sys-prefix --py"
