# Get editor completions based on the config schema
"$schema" ='https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the❯' symbol in the prompt with➜'
[character] # The name of the module we are configuring ischaracter'
success_symbol ='[➜](bold green)' # Thesuccess_symbol' segment is being set to➜' with the colorbold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
